{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-ebs-tagger.serviceAccountName" . }}
  labels:
{{ include "kube-ebs-tagger.labels" . | nindent 4 }}
{{- end -}}
