kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-ebs-tagger
subjects:
- kind: ServiceAccount
  name: kube-ebs-tagger
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kube-ebs-tagger
  apiGroup: rbac.authorization.k8s.io