kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-ebs-tagger
rules:
- apiGroups:
  - "apps"
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - get
  - create
  - update